pumbaa/models/photos.py
'''
Created on Nov 9, 2013

'''

import mongoengine as me

import datetime
import bson

from . import forums

LICENSE = [
         'COPYRIGHT',
         'CC-BY-NC-ND',
         'CC-BY-ND',
         'CC-BY-NC',
         'CC-BY-SA',
         'CC-BY-NC-SA',
         'CC-BY'
         ]

class Photo(me.EmbeddedDocument):
    id = me.ObjectIdField(required=True, default=bson.ObjectId)
    
    caption = me.StringField(default='')
    
    created_date = me.DateTimeField(required=True, default=datetime.datetime.now)
    updated_date = me.DateTimeField(required=True, default=datetime.datetime.now)

    image = me.ImageField(collection_name='images',
                          size=(1600, 1200, True),
                          thumbnail_size=(320, 240, True),
                          )
    
    comments = me.ListField(me.EmbeddedDocumentField(forums.Comment))
    license = me.StringField(required=True, default='COPYRIGHT', choices=LICENSE)
    
    user = me.ReferenceField("User", dbref=True, required=True)
    
    orientation = me.StringField(required=True, default='horizontal', choices=['vertical', 'horizontal'])
    
    def get_album(self):
        album = PhotoAlbum.objects(photos__id = self.id).first()
        return album

class PhotoAlbum(me.Document):
    meta = {'collection' : 'photo_albums'}
    
    name = me.StringField(required=True)
    description = me.StringField(default='')
    event_date = me.DateTimeField()
    shared = me.BooleanField(required=True, default=False)
    
    photos = me.ListField(me.EmbeddedDocumentField(Photo))
    status = me.StringField(required=True, default='draft')
    """ status: draft, publish, delete """
    
    created_date = me.DateTimeField(required=True, default=datetime.datetime.now)
    published_date = me.DateTimeField(required=True, default=datetime.datetime.now)
    updated_date = me.DateTimeField(required=True, default=datetime.datetime.now)
    
    comments = me.ListField(me.EmbeddedDocumentField(forums.Comment))

    user = me.ReferenceField("User", dbref=True, required=True)
        
    def get_photo(self, photo_id):
        for photo in self.photos:
            image = photo.image if photo.image.get() is not None else photo.vimage
            
            if image.filename == photo_id:
                return photo
                
            if str(photo.id) == photo_id:
                return photo
    
    def get_photo_index(self, photo_id):
        this_photo = None
        for i in range(0, len(self.photos)):
            photo = self.photos[i]
            image = photo.image if photo.image.get() is not None else photo.vimage
            try:
                if image.filename == photo_id:
                    this_photo = photo
            except:
                pass
            if str(photo.id) == photo_id:
                this_photo = photo
                
            if this_photo is not None:
                previous_ = None
                next_ = None

                if i-1 >= 0:
                    previous_ = self.photos[i-1]
                if i+1 < len(self.photos):
                    next_ = self.photos[i+1]

                return this_photo, previous_, next_

pumbaa/forms/photos.py
'''
Created on Nov 10, 2013

@author: boatkrap
'''
from wtforms import Form
from wtforms import fields
from wtforms.fields import html5
from wtforms import validators
import re
import datetime

class PhotoAlbum(Form):
    name = fields.TextField('Name', validators=[validators.InputRequired()])
    description = fields.TextAreaField('Description')
    shared = fields.BooleanField()
    event_date = html5.DateField(default=datetime.datetime.now())
    
    
class Photo(Form):
    image = fields.FileField('Image')
    license = fields.SelectField('License', validators=[validators.InputRequired()])
    

pumbaa/views/photos/__init__.py
'''
Created on Jul 14, 2012

@author: boatkrap
'''


from flask import (Blueprint, render_template, request, redirect, make_response,
current_app, url_for, send_file)


from PIL import Image
import tempfile

from pumbaa import models

from . import photo_albums

url_prefix = '/photo_album'
module = Blueprint('photos', __name__, url_prefix='/photos')

def register_blueprint(app):
    app.register_blueprint(module)
    app.register_blueprint(photo_albums.module, url_prefix=url_prefix)

 
@module.route('/<photo_album_id>/<photo_id>')
def view(photo_album_id, photo_id):
    
    photo_album = models.PhotoAlbum.objects.with_id(photo_album_id)
    photo = photo_album.get_photo(photo_id)
    
    extension = photo.image.filename[photo.image.filename.rfind('.')+1:]

    # if extension.lower() in ['jpg', 'jpeg']:
    #     response.content_type='image/jpeg'
    # elif extension.lower() in ['png']:
    #     response.content_type='image/png'
 
    img = Image.open(photo.image)
    img_format = img.format
    if photo.orientation == 'vertical':
        img = img.transpose(Image.ROTATE_90)
 
    tmp_img = tempfile.TemporaryFile()
             
    img.save(tmp_img, format=img_format)
    tmp_img.seek(0)
    
    return send_file(tmp_img,
                        attachment_filename=photo.image.filename,
                        as_attachment=True)
 
@module.route('/thumnail/<photo_album_id>/<photo_id>')
def thumbnail(photo_album_id, photo_id):

    photo_album = models.PhotoAlbum.objects.with_id(photo_album_id)
    photo = photo_album.get_photo(photo_id)
    
    extension = photo.image.filename[photo.image.filename.rfind('.')+1:]
    
    if photo.image.thumbnail:
        image = photo.image.thumbnail
        

    # if extension.lower() in ['jpg', 'jpeg']:
    #     response.content_type='image/jpeg'
    # elif extension.lower() in ['png']:
    #     response.content_type='image/png'
 
    
    img = Image.open(image)
    img_format = img.format
    
    if photo.orientation == 'vertical':
        img = img.transpose(Image.ROTATE_90)
 
    tmp_img = tempfile.TemporaryFile()
             
    img.save(tmp_img, format=img_format)
    tmp_img.seek(0)
 
    return send_file(tmp_img,
                        attachment_filename=photo.image.filename,
                        as_attachment=True)

pumbaa/templates/photos/photo_albums/index.jinja2
{% extends "/base/default-page.jinja2" %}

{% block title %}Photo Albums{% endblock %}
{% block description %}Photo Albums: {{ photo_albums | join(", ", attribute='name') }}{% endblock %}

{% block breadcrumb %}<a href="{{ url_for('photos.photo_albums.index') }}" class="breadcrumb">Photo Albums</a>{% endblock %}
{% block topic_title %}Photo Albums{% endblock %}
{% block content %}
<div class="row">
  {% for photo_album in photo_albums %}
    {% if photo_album.photos | count > 0 %}
      <div class="col s3" style="display: inline-flex;">
        <div class="card">
          <div class="card-image">
            <a href="{{url_for('photos.photo_albums.view', photo_album_id=photo_album.id)}}">
              <img src="{{url_for('photos.thumbnail', photo_album_id=photo_album.id, photo_id=photo_album.photos[0].image.filename)}}" alt="{{photo_album.name}}" width="100%">
            </a>
          </div>
          <div class="card-content">
            <span class="card-title">{{photo_album.name}}</span>
            <p>{{photo_album.description}}</p>
          </div>
          <div class="card-action">
            <a href="{{url_for('photos.photo_albums.view', photo_album_id=photo_album.id)}}">ชมภาพ</a>
          </div>
        </div>
      </div>
    {% endif %}
  {% endfor %}
</div>
{% endblock %}

pumbaa/templates/photos/photo_albums/photo-view.jinja2
{% extends '/base/topic-view.jinja2' %}

{% block title %}{{ photo_album.name + ": " + photo.image.filename }}{% endblock %}
{% block description %}{{ photo.caption if photo.caption|count > 0 else
photo.image.filename}}{% endblock %}
{% block where_am_i %}
<li><a href="{{ url_for('photos.photo_albums.index') }}">Photo Albums</a></li>
<li><a href="{{ url_for('photos.photo_albums.view',
photo_album_id=photo_album.id) }}">${photo_album.name}</a></li>
{% endblock %}
{% block topic_title %}{{ photo_album.name }}{% endblock %}

{% block content %}
<ul class="pager">
    <li class="previous{{' disabled' if pprevious == None else ''}}">
        {% if not pprevious == None %}
    <a href="{{ url_for('photos.photo_albums.photo_view',
    photo_album_id=photo_album.id, photo_id=pprevious.id) }}">&larr; Previous</a>
    {% else %}
  	<a href="#">&larr; Previous</a>
    {% endif %}
  </li>
  <li class="next{{' disabled' if pnext == None else ''}}">
      {% if not pnext == None %}
    <a href="{{ url_for('photos.photo_albums.photo_view',
    photo_album_id=photo_album.id, photo_id=pnext.id) }}">Next &rarr;</a>
    {% else %}
  	<a href="#">Next &rarr;</a>
    {% endif %}
  </li>
</ul>
<div class="row">
	<div class="col-sm-8 col-md-8 col-lg-9">
        <img class="img-rounded" alt="{{ photo.caption }}" src="{{
        url_for('photos.view', photo_album_id=photo_album.id,
        photo_id=photo.image.filename)}}" width="100%" />
	</div>
	<div class="col-sm-4 col-md-4 col-lg-3">
		<div class="well well-sm">
			<div>
				<div class="pull-left" style="margin-right: 3px;">
                    {{ photo.user.get_profile_picture() if
                    not photo.user.get_profile_picture() == None else '' }}
				</div>
				<div>
                    {{ photo.user.get_display_name() }}<br />
                    {{ photo.created_date.strftime('%d %b %Y %X') }}
				</div>
			</div>
            <p><b>License:</b> {{ photo.license }}</p>
            {% if photo.caption %}
            <p>{{ photo.caption }}</p>
            {% endif %}
			
			% if request.user == photo.user:
				<a class="btn btn-primary" href="${request.route_path('manager.photo_albums.delete_photo', photo_album_id=photo_album.id, photo_id=photo.id)}">Delete</a>
			% endif
			
		</div>
	</div>
</div>
{% endblock %}

{% block topic_footer %}
    {% set topic = photo %}
    {% include '/base/comments.jinja2' with context %}
{% endblock %}

pumbaa/templates/photos/photo_albums/photo_view.jinja2
{% extends '/base/topic_view.jinja2' %}

{% block title %}{{ photo_album.name + ": " + photo.image.filename }}{% endblock %}
{% block description %}{{ photo.caption if photo.caption|count > 0 else
photo.image.filename}}{% endblock %}
{% block where_am_i %}
<li><a href="{{ url_for('photos.photo_albums.index') }}">Photo Albums</a></li>
<li><a href="{{ url_for('photos.photo_albums.view',
photo_album_id=photo_album.id) }}">${photo_album.name}</a></li>
{% endblock %}
{% block topic_title %}{{ photo_album.name }}{% endblock %}

{% block content %}
<ul class="pager">
    <li class="previous{{' disabled' if pprevious == None else ''}}">
        {% if not pprevious == None %}
    <a href="{{ url_for('photos.photo_albums.photo_view',
    photo_album_id=photo_album.id, photo_id=pprevious.id) }}">&larr; Previous</a>
    {% else %}
  	<a href="#">&larr; Previous</a>
    {% endif %}
  </li>
  <li class="next{{' disabled' if pnext == None else ''}}">
      {% if not pnext == None %}
    <a href="{{ url_for('photos.photo_albums.photo_view',
    photo_album_id=photo_album.id, photo_id=pnext.id) }}">Next &rarr;</a>
    {% else %}
  	<a href="#">Next &rarr;</a>
    {% endif %}
  </li>
</ul>
<div class="row">
	<div class="col-sm-8 col-md-8 col-lg-9">
        <img class="img-rounded" alt="{{ photo.caption }}" src="{{
        url_for('photos.view', photo_album_id=photo_album.id,
        photo_id=photo.image.filename)}}" width="100%" />
	</div>
	<div class="col-sm-4 col-md-4 col-lg-3">
		<div class="well well-sm">
			<div>
				<div class="pull-left" style="margin-right: 3px;">
                    {{ photo.user.get_profile_picture() if
                    not photo.user.get_profile_picture() == None else '' }}
				</div>
				<div>
                    {{ photo.user.get_display_name() }}<br />
                    {{ photo.created_date.strftime('%d %b %Y %X') }}
				</div>
			</div>
            <p><b>License:</b> {{ photo.license }}</p>
            {% if photo.caption %}
            <p>{{ photo.caption }}</p>
            {% endif %}
			
			% if request.user == photo.user:
				<a class="btn btn-primary" href="${request.route_path('manager.photo_albums.delete_photo', photo_album_id=photo_album.id, photo_id=photo.id)}">Delete</a>
			% endif
			
		</div>
	</div>
</div>
{% endblock %}

{% block topic_footer %}
    {% set topic = photo %}
    {% include '/base/comments.jinja2' with context %}
{% endblock %}

pumbaa/templates/photos/photo_albums/view.jinja2
{% extends "/base/topic-view.jinja2" %}
{# <%! from pumbaa import models %> #}
{% block title %}{{ photo_album.name }}{% endblock %}
{% block description %}{{ photo_album.description }}{% endblock %}
{% block where_am_i %}
<li><a href="${request.route_path('photos.photo_albums.index')}">Photo Albums</a></li>
<li><a href="${request.route_path('photos.photo_albums.view', photo_album_id=photo_album.id)}">${photo_album.name}</a></li>
{% endblock %}
{% block topic_title %}{{ photo_album.name }}{% endblock %}
{% block content %}
<div style="padding: 5px;">
	<p class="text-primary">
    {{ photo_album.description }}
	</p>
  {% if photo_album.event_date is defined and photo_album.event_date is not none %}
	<p class="text-primary">
  เหตุการณ์นี้เกิดขึ้นเมื่อ {{photo_album.event_date.date()}}
	</p>
{% endif %}
</div>

{% for photo in photo_album.photos %}
<a href="{{ url_for('photos.photo_albums.photo_view',
photo_album_id=photo_album.id, photo_id=photo.id)}}" >
<img class="img-thumbnail" style="{{'width:200px;' if photo.orientation == 'horizontal' else 'height:150px;'}}" alt="{{ photo.caption }}" src="{{
url_for('photos.thumbnail', photo_album_id=photo_album.id,
photo_id=photo.image.filename)}}" />
	</a>
{% endfor %}

{% endblock %}
{% block topic_footer %}
{% set topic = photo_album %}
{% include "/base/comments.jinja2" with context %}
{% endblock %}