pumbaa/forms/topics.py
'''
Created on Oct 18, 2013

@author: boatkrap
'''
# from wtforms import Form
from flask_wtf import Form
from wtforms import fields
from wtforms import validators

from pumbaa import models
from .fields import TagListField

#from pyramid.threadlocal import get_current_request
#from pyramid.security import has_permission

def available_page_title(form, field):
    topic = models.Topic.objects(title=field.data, page=True).first()
    
    request = get_current_request()
    topic_id = request.matchdict.get('topic_id', None)
    if topic_id is not None:
        if str(topic.id) == topic_id:
            # edit case
            return
    
    if topic is not None:
        raise validators.ValidationError(
            'This page title: %s is available on system'% field.data)

def announce_tag_allow(form, field):
    tags = field.data
    request = get_current_request()
    for tag in tags:
        if tag in ['ประกาศ', 'ประกาศจากภาควิชา', 'announce']:
            if not has_permission('announce-tag', request.context, request):
                raise validators.ValidationError(
                    'This tag name "%s" is not allowed'% tag)

class Topic(Form):
    title = fields.TextField('Title', validators=[validators.InputRequired()])
    description = fields.TextAreaField('Description', validators=[validators.InputRequired()])
    tags = TagListField('Tags', validators=[validators.InputRequired(), announce_tag_allow])

class Page(Topic):
    title = fields.TextField('Title', validators=[validators.InputRequired(), available_page_title])
    comments_disable = fields.RadioField('Is disable comments', 
                                         choices=[('enable', 'enable'), ('disable', 'disable')],
                                         validators=[validators.InputRequired()])

class Comment(Form):
    message = fields.TextAreaField('Message', validators=[validators.InputRequired()])

pumbaa/views/accounts.py
'''
Created on Oct 13, 2013

@author: boatkrap
'''

from flask import (Blueprint, render_template, request, 
        redirect, make_response, current_app, url_for, session)
from authomatic.adapters import WerkzeugAdapter

from flask_login import login_required, current_user, login_user, logout_user
from flask_principal import identity_changed, Identity, AnonymousIdentity



from pumbaa import models, forms

import mongoengine as me

module = Blueprint('accounts', __name__)

# @view_config(route_name='register', renderer='/accounts/register.mako')
@module.route('/register')
def register():
    form = forms.accounts.Register(request.POST)
    
    if len(request.POST) > 0 and form.validate():
        password = form.data.get('password')
    else:
        return dict(
                form=form
                )
        
    user = models.User(**form.data)
    user.set_password(password)
    role = models.Role.objects(name='anonymous').first()
    user.roles.append(role)
    user.display_name = "%s %s" % (form.data.get('first_name'), form.data.get('last_name'))
    user.ip_address = request.environ['REMOTE_ADDR']
    user.display_name = "%s %s" % (form.data.get('first_name'), form.data.get('last_name'))
    user.save()
    
    return HTTPFound(location=request.route_path('index'))


# @view_config(route_name='login', renderer='/accounts/login.mako')
# @forbidden_view_config(renderer='/accounts/login.mako')
@module.route('/login', methods=['POST', 'GET'])
def login():
    # if request.user:
    #     return HTTPFound(location=request.route_path('home'))
    
    login_url = url_for('accounts.login')
    referrer = request.path
    
    if referrer == login_url:
        referrer = '/'

    came_from = request.args.get('came_from', referrer)
    message = ''
    # session = request.session
    # session['came_from'] = came_from
    
    form = forms.accounts.Login(request.form)

    if len(request.form) > 0 and form.validate():
        username = form.data.get('username')
        password = form.data.get('password')
        came_from = form.data.get('came_from')

        print('current app: ', current_app.config) 
        from pumbaa import crypto
        sm = crypto.SecretManager(current_app.config.get('SECRET_KEY'))

        hash_password = sm.get_hash_password(password)
        print('x===>:', hash_password)
        print('xx===>:', current_app.config.get('SECRET_KEY'))
        user = models.User.objects((me.Q(username=username) | me.Q(email=username))\
                                    & me.Q(password=hash_password)\
                                    & me.Q(status__ne='delete')).first()
        print('y===>:', user)

        if user:
            login_user(user)
            identity_changed.send(current_app._get_current_object(),
            	    identity=Identity(str(user.id)))

            # headers = remember(request, str(user.id))
            if came_from == '/':
                came_from = url_for('dashboard.index')
                
            return redirect(came_from)
        else:
            message = 'Username or password mismatch'

    form.came_from.data = came_from
    
    return render_template('/accounts/login.jinja2',
                form=form,
                message=message
                )





@module.route('/login/<provider_name>', methods=['GET', 'POST'])
def online_login(provider_name):
    """
    Login handler, must accept both GET and POST to be able to use OpenID.
    """

    # We need response object for the WerkzeugAdapter.
    response = make_response()

    # Log the user in, pass it the adapter and the provider name.
    result = authomatic.login(WerkzeugAdapter(request, response), provider_name)

    # If there is no LoginResult object, the login procedure is still pending.
    if result:
        if result.user:
            # We need to update the user to get more info.
            result.user.update()

            print('result =>', result.user.provider.name)
            print('data   =>', result.user.data)
            # flask login
            # login_user(user)
            user = models.User.objects(email=result.user.email).first()


            if not user:
                parameters = {
                        'providers__%s__id'%result.user.provider.name: result.user.data['id']
                        }

            if not user:
                user = models.User(
                        email=result.user.email,
                        username=result.user.name,
                        birth_date=result.user.birth_date,
                        name=result.user.name,
                        first_name=result.user.first_name,
                        last_name=result.user.last_name,
                        gender=result.user.gender
                        )

            if not user.email:
                email=result.user.email
                username=result.user.name
                birth_date=result.user.birth_date
                name=result.user.name
                first_name=result.user.first_name
                last_name=result.user.last_name
                gender=result.user.gender


            user.providers[result.user.provider.name] = result.user.data
            user.save()

            login_user(user)
            identity_changed.send(current_app._get_current_object(),
            	    identity=Identity(str(user.id)))

        nextx = request.args.get('next')
        return redirect(nextx or url_for('dashboard.index'))
        # The rest happens inside the template.
        # return render_template('/site/login-success.jinja2', result=result)

    # Don't forget to return the response.
    return response

@module.route('/logout')
@login_required
def logout():
    # Remove the user information from the session
    logout_user()

    # Remove session keys set by Flask-Principal
    for key in ('identity.name', 'identity.auth_type'):
        session.pop(key, None)

    # Tell Flask-Principal the user is anonymous
    identity_changed.send(current_app._get_current_object(),
                          identity=AnonymousIdentity())

    return redirect(request.args.get('next') or '/')


# @view_config(route_name='home', renderer='/accounts/home.mako', permission='login')
# @module.route('/dashboard')
# @login_required
# def dashboard():
#     return render_template('/accounts/dashboard.jinja2')

# @view_config(route_name='accounts.add_online_account', renderer='/accounts/add_online_account.mako', permission='login')
def add_online_account(request):
    return dict()

def add_new_online_profile(request):
    context = request.context
    domain = context.profile["accounts"][0]['domain']
    user_id  = context.profile["accounts"][0]['userid']
    
    
    profile = request.user.get_profile(domain)
    
    if profile:
        return HTTPFound(location=request.route_path('home'))
    
    if 'verifiedEmail' in context.profile:
        email = context.profile['verifiedEmail']
    else:
        email = context.profile['preferredUsername']+"@"+domain
    
    if 'name' in context.profile:
        first_name   = context.profile['name'].get('givenName', None)
        last_name    = context.profile['name'].get('familyName', None)
        if first_name is None:
            if 'formatted' in context.profile['name']:
                first_name = context.profile['name']['formatted']
                last_name = 'No Last Name'
    else:
        names = context.profile['displayName'].split(' ')
        first_name   = names[0]
        last_name    = names[-1]
        
    profile = models.Profile()
    profile.user_id = user_id
    profile.domain = domain
    profile.first_name = first_name
    profile.last_name = last_name
        
    profile.display_name = context.profile['displayName']

    if 'profile.php=' in context.profile['preferredUsername']:
        profile.username = profile.username.split('=')[-1]
    else:
        profile.username = context.profile['preferredUsername']
        
    profile.email = email
    profile.profile_source = context.profile
    
    # support old user accounts
    if request.user.display_name is None:
        request.user.display_name = request.user.username
    
    
    request.user.online_profiles.append(profile)
    request.user.save()
    
    return HTTPFound(location=request.route_path('home'))
    
# @view_config(
#     context='velruse.AuthenticationComplete',
# )
def online_login_complete(request):
    
    if request.user:
        return add_new_online_profile(request)
    
    context = request.context
    
    domain = context.profile["accounts"][0]['domain']
    user_id  = context.profile["accounts"][0]['userid']

    
    user = None
    user = models.User.objects(online_profiles__domain=domain,\
                                online_profiles__user_id=str(user_id)).first()
    if 'verifiedEmail' in context.profile:
        email = context.profile['verifiedEmail']
    else:
        email = context.profile['preferredUsername']+"@"+domain
    
    if 'name' in context.profile:
        first_name   = context.profile['name'].get('givenName', None)
        last_name    = context.profile['name'].get('familyName', None)
        if first_name is None:
            if 'formatted' in context.profile['name']:
                first_name = context.profile['name']['formatted']
                last_name = 'No Last Name'
    else:
        names = context.profile['displayName'].split(' ')
        first_name   = names[0]
        last_name    = names[-1]
    
    new_user = False
    if not user:
        new_user = True
        
        user = models.User.objects(email=email).first()
        if user:
            return Response('This Email is available on system, please contact administrator for registration')
        
        user = models.User()
        profile = models.Profile()
        profile.user_id = user_id
        profile.domain = domain
        
        
        user.first_name   = first_name

pumbaa/views/site.py
from flask import Blueprint, render_template, request, redirect, make_response, current_app, url_for
from authomatic.adapters import WerkzeugAdapter

from flask_login import login_required, current_user, login_user, logout_user
from flask_principal import identity_changed, Identity, AnonymousIdentity

import math
import datetime

# from .. import authomatic
from pumbaa import models
from pumbaa import forms

import mongoengine as me

module = Blueprint('site', __name__)

from . import topicutils

@module.route('/')
def index():
    recent_topics = models.Topic.objects(status='publish', type='topic').order_by('-published_date').limit(10).all()
    last_comments_topics_ = models.Topic.objects(status='publish', type='topic').order_by('-comments__published_date').limit(10).all()
    last_comments_topics = []
    for topic in last_comments_topics_:
        try:
            if len(topic.comments) > 0:
                last_comments_topics.append(topic)
        except Exception as e:
            print(e)
    
    photo_albums_ = models.PhotoAlbum.objects(status='publish').order_by('-published_date').limit(10).all()
    photo_albums = []
    for photo_album in photo_albums_:
        if len(photo_album.photos)> 0:
            photo_albums.append(photo_album)
            
    events = models.Event.objects((me.Q(status='publish') &
                                  (me.Q(started_date__gt=datetime.datetime.now().date()) | 
                                  me.Q(ended_date__gt=datetime.datetime.now())) &
                                  me.Q(event_type__in=['undergraduate', 'graduate', 'department'])))\
                        .order_by('+started_date')\
                        .limit(5).all()
    
    dep_announcement = models.Forum.get_forum('ประกาศจากภาควิชา')

    return render_template('/site/index.jinja2',
            dep_announcement=dep_announcement,
		   	recent_topics=recent_topics,
            last_comments_topics=last_comments_topics,
            photo_albums=photo_albums,
            events=events,
            topicutils=topicutils
            )
#            literatures=literatures,
#            num_rows=num_rows)

# @module.route('/login')
# def login():

#     form = forms.accounts.Login(request.form)    
    
#     return render_template('/site/login.jinja2', form=form)




# @module.route('/login/<provider_name>/', methods=['GET', 'POST'])
# def do_login(provider_name):
#     """
#     Login handler, must accept both GET and POST to be able to use OpenID.
#     """
#     if provider_name == 'pumbaa':
#         return

#     # We need response object for the WerkzeugAdapter.
#     response = make_response()

#     # Log the user in, pass it the adapter and the provider name.
#     result = authomatic.login(WerkzeugAdapter(request, response), provider_name)

#     # If there is no LoginResult object, the login procedure is still pending.
#     if result:
#         if result.user:
#             # We need to update the user to get more info.
#             result.user.update()

#             print('result =>', result.user.provider.name)
#             print('data   =>', result.user.data)
#             # flask login
#             # login_user(user)
#             user = models.User.objects(email=result.user.email).first()


#             if not user:
#                 parameters = {
#                         'providers__%s__id'%result.user.provider.name: result.user.data['id']
#                         }

#             if not user:
#                 user = models.User(
#                         email=result.user.email,
#                         username=result.user.name,
#                         birth_date=result.user.birth_date,
#                         name=result.user.name,
#                         first_name=result.user.first_name,
#                         last_name=result.user.last_name,
#                         gender=result.user.gender
#                         )

#             if not user.email:
#                 email=result.user.email
#                 username=result.user.name
#                 birth_date=result.user.birth_date
#                 name=result.user.name
#                 first_name=result.user.first_name
#                 last_name=result.user.last_name
#                 gender=result.user.gender


#             user.providers[result.user.provider.name] = result.user.data
#             user.save()

#             login_user(user)
#             identity_changed.send(current_app._get_current_object(),
#                     identity=Identity(str(user.id)))

#         nextx = request.args.get('next')
#         return redirect(nextx or url_for('dashboard.index'))
#         # The rest happens inside the template.
#         # return render_template('/site/login-success.jinja2', result=result)

#     # Don't forget to return the response.
#     return response

# @module.route('/logout')
# @login_required
# def logout():
#     # Remove the user information from the session
#     logout_user()

#     # Remove session keys set by Flask-Principal
#     for key in ('identity.name', 'identity.auth_type'):
#         session.pop(key, None)

#     # Tell Flask-Principal the user is anonymous
#     identity_changed.send(current_app._get_current_object(),
#                           identity=AnonymousIdentity())

#     return redirect(request.args.get('next') or '/')

pumbaa/templates/base/banner.jinja2
<div class="container">
	<div class="card-panel grey lighten-4">                          
        <h1 style="font-style: italic;"><a href="{{ url_for('site.index') }}">Hello, pumbaa.CoE!</a></h1>
	</div>
</div>

pumbaa/templates/base/comments.jinja2
{# <%block name="addition_header">
    <link rel="stylesheet" type="text/css" href="/public/css/pagedown.css" />
        
    <script type="text/javascript" src="/public/components/pagedown/Markdown.Converter.js"></script>
    <script type="text/javascript" src="/public/components/pagedown/Markdown.Sanitizer.js"></script>
    <script type="text/javascript" src="/public/components/pagedown/Markdown.Editor.js"></script>
    <script type="text/javascript" src="/public/components/pagedown/Markdown.Extra.js"></script>
    
    <script type="text/javascript" src="/public/components/google-code-prettify/src/prettify.js"></script> 
    <link rel="stylesheet" type="text/css" href="/public/components/google-code-prettify/src/prettify.css" />

## markdown script
<script type="text/javascript">
var converter;
(function () {

    ## converter = Markdown.getSanitizingConverter();
    converter = new Markdown.Converter();
    
    converter.hooks.chain("preBlockGamut", function (text, rbg) {
        return text.replace(/^ {0,3}""" *\n((?:.*?\n)+?) {0,3}""" *$/gm, function (whole, inner) {
            return "<blockquote>" + rbg(inner) + "</blockquote>\n";
        });
    });

    converter.hooks.chain("postConversion", function(text) {
        return text.replace(/\s*:::(:)*python\s*\n/, "");
    });
    
    Markdown.Extra.init(converter, {
      extensions: "all",
      highlighter: "prettify"
    });
    
})();
</script>

## google-code-prettify
<script type='text/javascript'>
document.addEventListener('DOMContentLoaded',function() {
    prettyPrint();
});
</script>

</%block>

#}
{#
<%
    comments = item.comments
    self.editor_counter = 0
%>
#}
{#% block name="do_comment" args="item">%#}
{% macro do_comment() %}
{#
<%
    	
    self.editor_counter += 1
    comment_url = None
    if type(item) == models.Topic:
    	comment_url = request.route_path('forums.comments.comment', topic_id=item.id)
    elif type(item) == models.Comment:
    	comment_url = request.route_path('forums.comments.reply', topic_id=item.get_topic().id, comment_id=item.id)
    elif type(item) == models.PhotoAlbum:
        comment_url = request.route_path('photos.photo_albums.comment', photo_album_id=item.id)
    elif type(item) == models.Photo:
        comment_url = request.route_path('photos.photo_albums.photo_comment', photo_album_id=item.get_album().id, photo_id=item.id)

    comments_disabled = False
    if hasattr(item, 'comments_disabled'):
        comments_disabled = item.comments_disabled
%>
#}
{## for disable comments #}

<section title="Share your opinion" class="well">
{% if current_user %}
  {#
    % if request.user.get_role('anonymous'):
        คุณยังไม่มีสิทธิ์ใช้งานส่วนแสดงความคิดเห็น กรุณาติดต่อสมาชิกที่รู้จักเพื่อยืนยันว่าคุณเป็นส่วนหนึ่งของ CoE
        % else:
  #}
    <form action="${comment_url}" method="post">
        <div class="row">
            <div class="col-md-1 col-lg-1">
            <section title="who comment">
                <p>
                {#{{ '' if request.user.get_profile_picture() == None else request.user.get_profile_picture() }}
                    <b>{{ current_user..username }}</b> #}
                </p>
            </section>
            </div>
            <div class="col-md-6 col-lg-6">
                <div id="wmd-button-bar-${self.editor_counter}"></div>
                <div class="form-group">
                    <label for="comment">Comment</label>
                    <textarea id="wmd-input-${self.editor_counter}" name="message" rows="5" class="form-control" placeholder="Share your comment"></textarea>
                </div>
            </div>
            <div class="col-md-5 col-lg-5">
                <b>Preview</b>
                <div id="wmd-preview-${self.editor_counter}" class="well well-sm"></div>
            </div>
        </div>
        <button type="submit">Share comment</button> 
        แนะนำวิธีการเขียน <a href="${request.route_path('pages.view', title='writing guideline')}">Markdown</a>
    </form>
    % endif
{% else %}
    <a href="${request.route_path('login')}">Log in</a> ก่อนแสดงความคิดเห็น
{% endif %}
</section>

{% endmacro %}

{% macro show_comment(comment, order='1') %}
{#
<%
    if comment.status == 'publish':
        render_comment_id.append({'id':"#%s"%comment.id, 'message':comment.message})
    else:
        render_comment_id.append({'id':"#%s"%comment.id, 'message':'ความเห็นนี้รอการพิจารณา'})
%>
#}
	<section title="comment">
        <div class="panel panel-info">
           <div class="panel-heading">
               ความคิดเห็นที่ {{ order }}
          </div>
          <div class="panel-body">
          	<div class="row">
          		<div class="col-sm-2 col-md-2 col-lg-2">
                    <p>{{ '' if comment.author.get_profile_picture() == None else comment.author.get_profile_picture() }}</p>
                    <p><b>{{ comment.author.username }}</b></p>
            		<p>
                        {{ comment.published_date.ctime() }}
            		</p>
          		</div>
          		<div class="col-sm-10 col-md-10 col-lg-10">
                    <div id="{{ comment.id }}">
                    {% if comment.status == 'publish' %}
{{comment.message}}
                    {% endif %}
                </div>
                {# <p class="text-right">
                {% if order.count('-') < 2 and (not (type(item) == models.PhotoAlbum or type(item) == models.Photo)) %}
                    <a href="" ng-click="reply_{{comment.id}} = !reply_${comment.id}">ตอบกลับ</a>
                {% endif %}
                </p>#}
                </div>
            </div>
          </div>
          <div class="panel-footer">
              {#% if order.count('-') < 2 and (not (type(item) == models.PhotoAlbum or type(item) == models.Photo)):
       	 		<div ng-show="reply_${comment.id}">
        		${self.do_comment(comment)}
        		</div>
				<div ng-hide="reply_${comment.id}"></div>
                % endif #}
            {% for i in range(0, comment.replies|count) %}
                {% set reply = comment.replies[i] %}
                {# set reply.topic = topic #}
                {% set suborder = (i+1)|string %}
                {{ show_comment(reply, order+"-"+suborder) }}
            {% endfor %}
          </div>
        </div>
        
    </section>
{% endmacro %}


{% if not comments_disabled %}
<section title="do comments">
    {{ do_comment() }}
</section>
{% endif %}
<section title="comments" style="margin-top: 10px;">
<h5><b>ความคิดเห็น</b></h5>
{% for order in range(0, topic.comments|count) %}
    {% set comment = topic.comments[order] %}
    {{ show_comment(comment, (order+1)|string) }}
{% endfor %}

{#
<script type="text/javascript">
var comments = ${json.dumps(render_comment_id) | n};
$( document ).ready(function() {
    comments.forEach(function(entry) {
        $(entry.id).html(converter.makeHtml(entry.message));
    });
});
</script>
#}
</section>

{## markdown editor #}
{#
<script type="text/javascript">
(function () {
	% for i in range(1, self.editor_counter+1):
    var editor${i} = new Markdown.Editor(converter,"-${i}");
    editor${i}.hooks.chain("onPreviewRefresh", prettyPrint); // google code prettify
    editor${i}.hooks.chain("onPreviewRefresh", function() {
        MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
    });
    editor${i}.run();
    % endfor
})();
</script>
#}

pumbaa/templates/base/default-dashboard.jinja2
{% extends "/base/base-layout.jinja2" %}
{% block keywords %}CoE, PSU, Computer Engineering, Prince of Songkla
University, Community{% endblock %}
{% block description %}This site is for people in CoE{% endblock %}

{% block jsmodule %}
System.import('css-framework').then(() => {
	System.import('dashboard'); 
});
{% endblock %}

{% block additional_head %}
<style>
  header, main, footer {
    padding-left: 300px;
  }

  @media only screen and (max-width : 992px) {
    header, main, footer {
      padding-left: 0;
    }
  }
</style>
{% endblock %}

{% block header %}
  {% include "/base/toolbar-dashboard.jinja2" %}
{% endblock header%}

{% block main %}
    <div class="row">
      <div class="col s12">
        <nav>
          <div class="nav-wrapper grey lighten-1">
            <div class="col s12">
              <a href="{{ url_for('dashboard.index') }}" class="breadcrumb">Dashboard</a>
              {% block breadcrumbs %}{% endblock breadcrumbs %}
            </div>
          </div>
        </nav> 
      </div>
    </div>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  {% endblock main %}

  {% block footer %}
    {% include "/base/footer.jinja2" %}
  {% endblock %}

pumbaa/templates/base/default-page.jinja2
{% extends "/base/base-layout.jinja2" %}

{% block title %}Forums{% endblock %}
{% block keywords %}CoE, PSU, Computer Engineering, Prince of Songkla University, Community{% endblock %}
{% block description %}This site is for people in CoE{% endblock %}

{% block main %}
  <div class="container">
    <div class="row">
      <nav>
        <div class="nav-wrapper light-blue darken-3">
          <div class="col s12" style="padding-left:30px;">
            {% block breadcrumb %}
            <a href="{{ url_for('forums.index') }}" class="breadcrumb">Forums</a>
            {% endblock %}
          </div>
        </div>
      </nav>
    </div>
    <div class="row">
      <div class="col s12">
        <h3>{%block topic_title %}Topic{% endblock %}</h3>
      </div>
    </div>

    {%block topic_content %}
    <div class="row">
      <div class="col s12">
        {%block content %}Content{% endblock %}
      </div>
    </div>
    {% endblock topic_content %}

    {% block topic_footer %}{% endblock %}
    {% block comments %}{% endblock %}
  </div>

{% endblock main %}

pumbaa/templates/base/default.jinja2
{% extends "/base/base-layout.jinja2" %}
{% block keywords %}CoE, PSU, Computer Engineering, Prince of Songkla
University, Community{% endblock %}
{% block description %}This site is for people in CoE{% endblock %}

{% block main %}
  <div class="container">
	{% block content %}{% endblock content %}
  </div> 
{% endblock main %}

pumbaa/templates/base/footer.jinja2
    <div class="row">
        <style type="text/css">
        .head-footer {
            background-color: #01579b; 
            border: 1px solid #bce8f1;
            font-weight: bold;
            color: white;
        }
        </style>
        <div class="col s3 m3 l3">
            <section title="About Pumbaa">
                <div class="well well-sm head-footer">
                    About Pumbaa
                </div>
                <ul class="list-unstyled">
                  <li><a href="${request.route_path('pages.view', title='about')}">เกี่ยวกับ Pumbaa</a></li>
                  <li><a href="${request.route_path('pages.view', title='history')}">ประวัติ Pumbaa</a></li>
                  <li><a href="${request.route_path('pages.view', title='contact')}">ติดต่อเรา</a></li>
                  <li><a href="${request.route_path('pages.view', title='writing guideline')}">แนะนำการเขียน</a></li>
                  <li><a href="${request.route_path('pages.view', title='become member')}">จะมาเป็นสมาชิกได้อย่างไร</a></li>
                </ul>
            </section>
        </div>
        <div class="col s3 m3 l3">
            <section title="Other">
                <div class="well well-sm head-footer">
                    Other
                </div>
                <ul class="list-unstyled">
                  <li><a href="${request.route_path('forums.index')}">กระดานข่าว</a></li>
                  <li><a href="${request.route_path('forums.topics.index')}">กระทู้ทั้งหมด</a></li>
                  <li><a href="${request.route_path('forums.tags.index')}">ป้ายกำกับ</a></li>
                  <li><a href="${request.route_path('forums.feeds')}">Atom</a></li>
                  <li><a href="https://www.facebook.com/groups/115299811878766">Pumbaa on Facebook</a></li>
                </ul>
            </section>
        </div>
        <div class="col s3 m3 l3">
            <section title="CoE Eng PSU">
                <div class="well well-sm head-footer">
                    เว็บไซต์
                </div>
                <ul class="list-unstyled">
                  <li><a href="http://www.coe.psu.ac.th">Department of Computer Engineering</a></li>
                  <li><a href="http://www.eng.psu.ac.th">Faculty of Engineering</a></li>
                  <li><a href="http://www.psu.ac.th">Prince of Songkla University</a></li>
                </ul>
            </section>
        </div>
        <div class="col s3 m3 l3">
            <section title="Development">
                <div class="well well-sm head-footer">
                    Development
                </div>
                <ul class="list-unstyled">
                  <li><a href="https://github.com/sdayu/pumbaa">Pumbaa on GitHub</a></li>
                  <li><a href="https://github.com/sdayu/pumbaa/issues">แจ้งข้อผิดพลาด</a></li>
                  <li><a href="${request.route_path('forums.view', name='Development')}">พูดคุยเกี่ยวกับการพัฒนา Pumbaa</a></li>
                </ul>
            </section>
        </div>
    </div>

pumbaa/templates/base/toolbar.jinja2
{% macro navlink() -%}
  {% if current_user.is_authenticated %}
    <li><a href="{{ url_for('dashboard.index') }}">Dashboard</a></li>
    <li><a href="{{ url_for('accounts.logout') }}">Logout</a></li>
  {% else %}
    <li><a href="{{ url_for('accounts.login') }}">Login</a></li>
  {% endif %}
{% endmacro %}


  <nav class="light-blue darken-4" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{{ url_for('site.index') }}" class="brand-logo">Pumbaa</a>
      <ul class="right hide-on-med-and-down">
          {{ navlink() }}
      </ul>

      <ul id="nav-mobile" class="side-nav">
          {{ navlink() }}
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

pumbaa/templates/base/topic-view.jinja2
{% extends "/base/default-page.jinja2" %}

{% block jsmodule %}
  System.import('css-framework').then(() => {
    System.import('topic-view');
  });
{% endblock %}